#Lista de compras:

print("Geral: ")
print("Leite Ninho")
print("Café em pó solúvel - Nescafé")
print("Pão")
print("Macarrão")
promocao1 = input("Azeite está em promoção? sim ou não? ")
if promocao1 == ("sim") or promocao1 == ("Sim"):
    print("Azeite")
else:
    print("Deixa o azeita pra próxima.")
print("")
print("Frios:")
print("Requeijão")
print("Queijo")
print("Mortadela")
print("")
print("Material de Limpeza: ")
print("Sabão Líquido - Ariel Downy Refil")
print("Detergente")
print("Papel Higiênico")
print("")
print("Bebidas: ")
print("Água com Gás 5 packs")
print("Energético 4 und")
print("")
print("Hortifruti: ")
print("Batata")
print("Cenoura")
print("Cebola")
print("Brócolis")
print("Alface")
print("Couve")
print("Tomate")
print("Laranja")
print("Limão")
print("Morango")
print("Maracujá")
print("Banana")
print("")
promocao2 = input("Doce está em promoção? sim ou não? ")
if promocao2 == ("sim") or promocao2 == ("Sim"):
    print("Doce")
else:
    print("Sem doce hoje.")
print("")